### ISSUE TITLE
missing origin

### ISSUE THREAD

**Issue by NathanielPenn** [learn-co-curriculum/python-p4-project-template#1]
### Canvas Link

https://learning.flatironschool.com/courses/6259/pages/phase-4-full-stack-application-project-template?module_item_id=551558

### Concern

I was having errors when I was doing the create your own git repo section. 

Head back to the command line and enter git remote add <project name> <github url>. This will map the remote repository to your local repository. Finally, push your first commit with git push -u origin main.

shouldnt the line say git remote add origin <project name> <github url>. ?
not sure but adding origin got my repo up and running. 

### Suggested Changes

add origin to the code

**Comment by professor-ben** [comment]
It certainly should! This should be fixed now. Thanks for contributing to the FIS curriculum (and on being the first contributor to this repo!)

-Ben
