### ISSUE TITLE
Flask DB initialization issue related to presence of Migrations subdirectory

### ISSUE THREAD

**Issue by djprofessorkash** [learn-co-curriculum/python-p4-project-template#6]
### Canvas Link

https://learning.flatironschool.com/courses/6275/pages/phase-4-full-stack-application-project-template

### Concern

Attempting to follow the instructional guide on cloning the `python-p4-project-template` repo and create a Flask project results in errors due to an error in how Flask setup is handled. 

The template repo need not contain the nested subdirectory `server/migrations` – it is easier for students to generate this migrations folder from scratch using `flask db init`. Additionally, following the instructions directly (executing `flask db init migrations`) results in an error. 

Therefore, `server/migrations` should be removed from the template repository and the Canvas and README instructions should be updated such that the initial setup instructions state to execute `flask db init` rather than `flask db init migrations`.

**Comment by linda-seiter** [comment]
#7 fix
